# Generated by Django 5.2.7 on 2025-10-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('profile_pic', models.ImageField(upload_to='profile/')),
                ('resume', models.FileField(upload_to='resume/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
